### ISSUE TITLE
Failed to install 'gwann'

### ISSUE THREAD

**Issue by Boorn123** [jhagenauer/gwann#1]
Hi, I tried to install gwann with this command in Windows 10:
`devtools::install_github("jhagenauer/gwann",INSTALL_opts=c("--no-multiarch"))`
I got this error:
`Error: (converted from warning) package 'rJava' was built under R version 3.6.3`
`Execution halted`
`ERROR: lazy loading failed for package 'gwann'`
`* removing 'C:/Users/boenz/Documents/R/win-library/3.6/gwann'`
`Error: Failed to install 'gwann' from GitHub:`
`(converted from warning) installation of package`
`'C:/Users/boenz/AppData/Local/Temp/Rtmp6pqJmL/filed243a522a3/gwann_0.0.1.tar.gz’ had non-zero exit status`
Do yo have any suggestion how to solve the problem?

Thank you very much!

**Comment by jhagenauer** [comment]
Hi,
the problem is that your R version does is not 3.6.3. This is not a problem but R decideds to abort the installation anyways.
I changed the install instructions to change this behaviour. Now it should install even if the R versions do not match.
Thanks!
