### ISSUE TITLE
rJava not recognised

### ISSUE THREAD

**Issue by p91g** [jhagenauer/gwann#10]
Hi there,

I have installed and loaded rJava, but when I run the following code, I get the error message:

SCRIPT

**library(rJava)

Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
if (!require("devtools"))
  install.packages("devtools",INSTALL_opts="--no-multiarch")
devtools::install_github("jhagenauer/gwann")**

CONSOLE

Error: package or namespace load failed for 'rJava':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: JAVA_HOME cannot be determined from the Registry
Error : package 'rJava' could not be loaded
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/patri/Documents/R/win-library/4.1/gwann'
Warning message:

**Comment by jhagenauer** [comment]
Hi,

the message suggests that your Java-installation is not correct, in particular you have not set JAVA_HOME environment-variable.

**Comment by p91g** [comment]
Thank you for the quick response. I set the environment variable for java home. I now get the following error. I have the 64 bit version of java installed.

Error: package or namespace load failed for 'rJava':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/Documents/R/win-library/4.1/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error : package 'rJava' could not be loaded
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/Documents/R/win-library/4.1/gwann'

**Comment by jhagenauer** [comment]
There seems to be an issue between x64 vs i386 on your system. This is not a gwann problem.

Best
Julian
