### ISSUE TITLE
Error in install package gwann

### ISSUE THREAD

**Issue by SoviaIndrawati** [jhagenauer/gwann#13]
Hello, Mr. Julian.
I tried to install gwann with this command in Windows 10 :
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
if (!require("devtools"))
install.packages("devtools")
devtools::install_github("jhagenauer/gwann",INSTALL_opts=c("--no-multiarch"))

And i got this error:
Downloading GitHub repo jhagenauer/gwann@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet, :
download from 'https://api.github.com/repos/jhagenauer/gwann/tarball/HEAD' failed
Warning message:
In devtools::install_github("jhagenauer/gwann", INSTALL_opts = c("--no-multiarch")) :
Arguments in ... must be used.
✖ Problematic argument:
• INSTALL_opts = c("--no-multiarch")
ℹ Did you misspell an argument name?

Do you have any suggestion how to solve the problem?
Thank you so much in advance. May you have a blessed day.

**Comment by jhagenauer** [comment]
Does this work?

```
library(devtools)
options(devtools.install.args = "--no-multiarch")   
install_github("jhagenauer/gwann")
```

What OS are you using?

Best
Julian

**Comment by SoviaIndrawati** [comment]
it has been successfully installed, thank you for your reply
