### ISSUE TITLE
Error in .jcall

### ISSUE THREAD

**Issue by SoviaIndrawati** [jhagenauer/gwann#14]
Hello Mr. Julian,
I tried your program code and encountered an error in .jcall:
SCRIPT :
r<-.jcall(obj="supervised.nnet.gwann.GWANN_RInterface",method="run",returnSig = "Lsupervised/nnet/gwann/Return_R;",
          
          .jarray(x_train,dispatch=T),
          y_train,
          .jarray(w_train,dispatch=T),
          
          .jarray(x_pred,dispatch=T),
          y_pred,
          .jarray(w_pred,dispatch=T),
          
          norm,nrHidden,batchSize,optimizer,lr,linOut,
          kernel,bandwidth,adaptive,
          bwSearch,
          
          bwMin,bwMax,steps,iterations,patience,folds,repeats,permutations,threads)

CONSOLE :
Error in .jcall(obj = "supervised.nnet.gwann.GWANN_RInterface", method = "run",  : 
  method run with signature ([[D[D[[D[[D[D[[DZDDLjava/lang/String;DZLjava/lang/String;DZLjava/lang/String;DDDDDDDDD)Lsupervised/nnet/gwann/Return_R; not found

Do you have any suggestions on how to solve the problem?
Thank you so much in advance. May you have a blessed day

**Comment by jhagenauer** [comment]
Dear Sovia,

 

please use only the example-code from the readme-file. The  code you showed me ist only for testing purposes.

 

Best

Julian

 
 

Gesendet: Samstag, 21. Oktober 2023 um 06:40 Uhr
Von: "SoviaIndrawati" ***@***.***>
An: "jhagenauer/gwann" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [jhagenauer/gwann] Error in .jcall (Issue #14)


 

Hello Mr. Julian,
I tried your program code and encountered an error in .jcall:
SCRIPT :
r<-.jcall(obj="supervised.nnet.gwann.GWANN_RInterface",method="run",returnSig = "Lsupervised/nnet/gwann/Return_R;",

      .jarray(x_train,dispatch=T),
      y_train,
      .jarray(w_train,dispatch=T),

      .jarray(x_pred,dispatch=T),
      y_pred,
      .jarray(w_pred,dispatch=T),

      norm,nrHidden,batchSize,optimizer,lr,linOut,
      kernel,bandwidth,adaptive,
      bwSearch,

      bwMin,bwMax,steps,iterations,patience,folds,repeats,permutations,threads


)

CONSOLE :
Error in .jcall(obj = "supervised.nnet.gwann.GWANN_RInterface", method = "run", :
method run with signature ([[D[D[[D[[D[D[[DZDDLjava/lang/String;DZLjava/lang/String;DZLjava/lang/String;DDDDDDDDD)Lsupervised/nnet/gwann/Return_R; not found

Do you have any suggestions on how to solve the problem?
Thank you so much in advance. May you have a blessed day

**Comment by SoviaIndrawati** [comment]
oh i see, thanks for answer.

So how to find the importance value? is it really like this?
Code :
# importance
 s<-cbind( x1=diag(r$importance[1,,]),
x2=diag(r$importance[2,,]),data[,c("u","v")] )

Console
 Error in r$importance[1, , ] : object of type 'S4' is not subsettable

but there is an error in the code. How about this?
Thank you so much. Hope for your help,
May you babe a blessed day


Min, 22 Okt 2023 pukul 23.30 Julian ***@***.***> menulis:

**Comment by SoviaIndrawati** [comment]
I got the code by copying from the gwann_example_test.R file in the
examples folder on github.
 it contains the code #importance,
Is it true that this is used to find variable importance values?



Sel, 24 Okt 2023 pukul 16.33 Julian ***@***.***> menulis:

**Comment by jhagenauer** [comment]
Hi Sovia,

 

I advice you not to use the feature importance option of GWANN. It's not tested yet and full of bugs. Just set permutations to 0 and ignore the importance stuff.

 

Best

Julian

 
 

Gesendet: Dienstag, 24. Oktober 2023 um 11:54 Uhr
Von: "SoviaIndrawati" ***@***.***>
An: "jhagenauer/gwann" ***@***.***>
Cc: "Julian" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [jhagenauer/gwann] Error in .jcall (Issue #14)


 
I got the code by copying from the gwann_example_test.R file in the
examples folder on github.
it contains the code #importance,
Is it true that this is used to find variable importance values?



Sel, 24 Okt 2023 pukul 16.33 Julian ***@***.***> menulis:
