### ISSUE TITLE
Is it possible to export only the trained GWANN model?

### ISSUE THREAD

**Issue by franciscoseger** [jhagenauer/gwann#15]
Hello, jhagenauer,

I would like to know if it would be possible to export only the trained model for later prediction of values. 

In my case, I have a dataset with 6253 observations and 14 independent variables. I want to test the impact on prediction by changing some independent variables. It has been computationally expensive to run the entire model to perform this test. Would it be possible to separate the code into training and prediction?

I thank you in advance.

**Comment by jhagenauer** [comment]
Hi, 

yes, you can save/serialize your trained model using, e.g., the saveRDS and load it with loadRDS. This should not be a problem.

Best
Julian

**Comment by franciscoseger** [comment]
Thank you for your reply.
The Java code only returns a list of results to R, not the trained model. I may be wrong, but I don’t think I can apply a predict function with this.

**Comment by jhagenauer** [comment]
Yes, you are right. Currently, there is not preditc-function for GWANN. Predictions are made when building the model. This should be implemented in the future but there is currently no plan for this. A predict-function is also somewhat limited in practice since for GWANN (and GWR) predictions only make sense for locations which have already been considered during the model building phase.

**Comment by franciscoseger** [comment]
The idea would be to work with the same locations, adding ±10% to the independent variables and analyzing the effect of this on the dependent variable.
I understand the complexity of implementing this code but I thank you for your response and congratulate you on the excellent work.

**Comment by jhagenauer** [comment]
I took a few hours and implemented a predict function. Please check it out and if you have any questions, don't hesitate to ask me.
 

Gesendet: Mittwoch, 08. November 2023 um 13:57 Uhr
Von: "franciscoseger" ***@***.***>
An: "jhagenauer/gwann" ***@***.***>
Cc: "Julian" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [jhagenauer/gwann] Is it possible to export only the trained GWANN model? (Issue #15)


 

The idea would be to work with the same locations, adding ±10% to the independent variables and analyzing the effect of this on the dependent variable.
I understand the complexity of implementing this code but I thank you for your response and congratulate you on the excellent work.

**Comment by franciscoseger** [comment]
I tested the implementation and it worked perfectly. Thank you very much for the quick response and implementation.
