### ISSUE TITLE
Hello, I would like to ask what is the main difference between this article of yours and the GNNWR cited in the article?

### ISSUE THREAD

**Issue by jaycecd** [jhagenauer/gwann#2]
In my opinion, both articles use artificial neural networks to find geographical weights. 
So, can you help me a little bit? Thank you ~~

The article address is as follows:
https://www.tandfonline.com/doi/full/10.1080/13658816.2019.1707834?src=recsys

**Comment by jaycecd** [comment]
Thank you very much for your quick reply,
I probably know the difference between the two articles. There is another question I need to ask you. Your article says:
![image](https://user-images.githubusercontent.com/33342388/138062069-618e4249-056b-4a4e-89ad-f8a8efe9f857.png)
I want to know how to assign neurons to geographic space?random?

**Comment by jhagenauer** [comment]
You assing the neurons to the locations for which you want to predict some value. 

Best
Julian
