### ISSUE TITLE
R aborted when loading gwann

### ISSUE THREAD

**Issue by yzhang937** [jhagenauer/gwann#9]
Hi Julian, may I know the version of the rJave, since every time I try to import the gawnn (this line -- library(gwann)), the R sessions is aborted.

**Comment by jhagenauer** [comment]
Hi,
which version do you use? Could you test if rJava works on your machine properly? What is the exact error message?
Thanks

**Comment by ldxm9527** [comment]
hello, jhagenauer
I meet the same problem in the same line with yzhang937.
Once run the code _library(gwann)_ and then my ide 100% crash.
My runtime environment FYI:
windows 10, JDK11, rJava_1.0-6 sp_1.5-0
